<script setup>
// @ts-check
import {computed, ref, watch} from 'vue';
import TexturePicker from './TexturePicker.vue';
import CheckField from './fields/CheckField.vue';
import ColorField from './fields/ColorField.vue';
import RangeField from './fields/RangeField.vue';
import textures from '../../catalog/textures.json';
import materials from '../../catalog/materials.json';
import {SELECTION_WALL} from '../composables/useSelection.js';
import {NO_TINT} from '../../scripts/blueprint.js';

/**
 * Wall and floor surfaces.
 *
 * Sprint S7, replacing the dat.GUI "Wall and Floor (3D)" folder.
 *
 * The demo showed both dropdowns whichever you clicked, and each acted only if
 * it had something to act on - so with a wall selected the Floor dropdown did
 * nothing, and "All Walls In Room" did nothing either, since it is the Room
 * that knows its walls. Here the panel shows the picker that applies to what
 * you actually clicked, and the room-wide toggle appears with a floor, which is
 * the only time it does anything.
 *
 * The behaviour underneath is unchanged: `HalfEdge.setTexture` for a wall,
 * `Room.setTexture` for a floor, `Room.setRoomWallsTexture` for all of a room's
 * walls at once.
 *
 * ## What H1 added, and where it put it
 *
 * A surface is more than its image since RM-011 H1: a tint, a rotation and an
 * offset, and for a room a **ceiling** as well, which RM-007's gap Q-4 named and
 * nothing here offered. Those controls sit under the picker rather than beside
 * it because they modify the thing the picker chose - you pick a brick and then
 * you turn it, and a panel that reads top to bottom in that order needs no
 * explaining.
 *
 * The tint is a *multiply*, so white is not a colour, it is the absence of one -
 * which is why the reset is offered as a button rather than by expecting anybody
 * to find `#ffffff` on a wheel.
 *
 * ## Two catalogs, one picker
 *
 * H1's library is thirty CC0 materials with a roughness map each, and it is a
 * second file rather than an extension of `textures.json` because the two have
 * different lifetimes: `textures.json` is the demo's seven, hand-written, and
 * every saved design that has ever named a texture names one of them.
 * `materials.json` is generated by `tools/fetch-materials.mjs` and regenerated
 * whenever the library changes. Concatenating them here - the demo's set first,
 * so a design made before H1 still finds its swatch where it was - is the whole
 * integration, because a material entry is a superset of a texture entry.
 */

const props = defineProps({
	selection: {type: Object, required: true},
});

const forAllWalls = ref(false);

const isWall = computed(() => props.selection.type === SELECTION_WALL);
const target = computed(() => props.selection.object);

/**
 * Bumped after every change so the "current" highlight re-reads. The model has
 * no event for a texture change - `setTexture` writes the wall's front/back
 * texture object and returns.
 */
const revision = ref(0);

const currentTexture = computed(() =>
{
	// Touch the counter so this recomputes after a pick.
	void revision.value;
	return target.value.getTexture ? target.value.getTexture() : null;
});

/** The demo's seven first, then the library, for both surfaces. */
const wallSwatches = computed(() => [...textures.wall, ...materials.wall]);
const floorSwatches = computed(() => [...textures.floor, ...materials.floor]);

/**
 * The maps that came with the picture, applied on top of the picture.
 *
 * `setTexture` deliberately *keeps* the material - picking a different brick is
 * not a decision to lose the colour you tinted it. A roughness map is the one
 * part of a material that does not work that way, because it belongs to the
 * image rather than to the person: the bumps in a plaster's roughness map are
 * that plaster's bumps, and leaving them on a marble would be a bug rather than
 * a preserved choice.
 *
 * So every pick writes the slot, to the entry's map or to null. Picking one of
 * the demo's seven clears it, which is what makes the two catalogs mix.
 *
 * @param {Object} surface The wall side or room to write to.
 * @param {Object} texture The catalog entry that was picked.
 */
function applyMaps(surface, texture)
{
	if (surface && surface.setMaterial)
	{
		surface.setMaterial({roughnessMap: texture.roughnessMap || null});
	}
}

function applyWall(texture)
{
	target.value.setTexture(texture.url, texture.stretch, texture.scale);
	applyMaps(target.value, texture);
	revision.value++;
}

function applyFloor(texture)
{
	target.value.setTexture(texture.url, texture.stretch, texture.scale);
	applyMaps(target.value, texture);
	revision.value++;
}

function applyRoomWalls(texture)
{
	target.value.setRoomWallsTexture(texture.url, texture.stretch, texture.scale);
	// The walk belongs to the model, which already owns one for the texture. A
	// second copy here would put a DCEL traversal in a Vue component and give the
	// two of them a chance to disagree about what "this room's walls" means.
	target.value.setRoomWallsMaterial({roughnessMap: texture.roughnessMap || null});
	revision.value++;
}

/** What the selected surface is made of, defaults filled in (RM-011 H1). */
const material = computed(() =>
{
	void revision.value;
	return target.value && target.value.getMaterial
		? target.value.getMaterial()
		: {color: NO_TINT, rotation: 0, offsetX: 0, offsetY: 0};
});

/** @param {Object} changes */
function applyMaterial(changes)
{
	if (target.value && target.value.setMaterial)
	{
		target.value.setMaterial(changes);
		revision.value++;
	}
}

/**
 * The ceiling's tint, or white when the room has not been given one.
 *
 * A ceiling with no record renders the profile's colour, so the swatch shows
 * white - the tint that would change nothing - rather than showing the profile's
 * grey and implying somebody chose it.
 */
const ceilingTint = computed(() =>
{
	void revision.value;
	const ceiling = !isWall.value && target.value.getCeiling && target.value.getCeiling();
	return (ceiling && ceiling.color) || NO_TINT;
});

/** @param {string} color */
function applyCeiling(color)
{
	target.value.setCeiling(color === NO_TINT ? null : {color});
	revision.value++;
}

/** Back to no tint at all, which is not the same as picking white by hand. */
function clearTint()
{
	applyMaterial({color: NO_TINT});
}

function pickWallTexture(texture)
{
	if (isWall.value)
	{
		applyWall(texture);
		return;
	}
	// A floor is selected: this picker is offering to retexture the room's walls.
	applyRoomWalls(texture);
}

watch(() => props.selection, () => {forAllWalls.value = false; revision.value++;});
</script>

<template>
	<section class="inspector-section">
		<h2 class="inspector-heading">{{ isWall ? 'Wall surface' : 'Room surfaces' }}</h2>

		<template v-if="isWall">
			<TexturePicker
				label="Wall" :textures="wallSwatches" :current="currentTexture"
				@select="pickWallTexture" />
		</template>

		<template v-else>
			<TexturePicker
				label="Floor" :textures="floorSwatches" :current="currentTexture"
				@select="applyFloor" />
			<CheckField v-model="forAllWalls" label="Also retexture this room's walls" />
			<TexturePicker
				label="Walls in this room" :textures="wallSwatches"
				:disabled="!forAllWalls" :current="null"
				@select="pickWallTexture" />
		</template>

		<h3 class="inspector-subheading">{{ isWall ? 'Wall material' : 'Floor material' }}</h3>
		<ColorField
			:model-value="material.color" label="Tint"
			@update:model-value="(value) => applyMaterial({color: value})" />
		<button
			v-if="material.color !== NO_TINT"
			type="button" class="btn btn-outline" title="Remove the tint"
			@click="clearTint">
			Clear tint
		</button>
		<RangeField
			:model-value="material.rotation" label="Rotation" :min="0" :max="359" :step="1" unit="°"
			@update:model-value="(value) => applyMaterial({rotation: value})" />
		<RangeField
			:model-value="material.offsetX" label="Offset across" :min="-1" :max="1" :step="0.02"
			@update:model-value="(value) => applyMaterial({offsetX: value})" />
		<RangeField
			:model-value="material.offsetY" label="Offset along" :min="-1" :max="1" :step="0.02"
			@update:model-value="(value) => applyMaterial({offsetY: value})" />

		<template v-if="!isWall">
			<h3 class="inspector-subheading">Ceiling</h3>
			<ColorField
				:model-value="ceilingTint" label="Ceiling tint"
				@update:model-value="applyCeiling" />
		</template>
	</section>
</template>
